version: '3.8'

services:
  kd-caa-app:
    build: .
    container_name: kd-caa-prediction
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    # volumes:
      # 개발 시 코드 변경사항을 실시간 반영하려면 아래 주석 해제
      # - .:/app
    restart: unless-stopped 